"""phase2_core_domain

Revision ID: 19845b2e628d
Revises: 
Create Date: 2026-09-08 00:44:02.364076

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19845b2e628d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('case_no_internal', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('goal_summary', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','ARCHIVED')", name='ck_cases_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_owner_updated', 'cases', ['owner_user_id', 'updated_at'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_workflow_templates_code_version')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_case_created', 'audit_logs', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('case_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=200), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('life_status', sa.String(length=32), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("life_status IN ('ACTIVE','VOID')", name='ck_materials_life'),
    sa.CheckConstraint("parse_status IN ('PENDING','RUNNING','SUCCEEDED','FAILED')", name='ck_materials_parse'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_materials_case_created', 'case_materials', ['case_id', 'created_at'], unique=False)
    op.create_table('case_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('party_key', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('party_type', sa.String(length=32), nullable=False),
    sa.Column('identifiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('confirm_decision_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("layer IN ('CANDIDATE','CONFIRMED','REJECTED','SUPERSEDED')", name='ck_case_parties_layer'),
    sa.CheckConstraint("party_type IN ('ORG','PERSON')", name='ck_case_parties_type'),
    sa.CheckConstraint("role IN ('PLAINTIFF','DEFENDANT','THIRD_PARTY','OTHER')", name='ck_case_parties_role'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['confirm_decision_id'], ['human_decisions.id'], name='fk_case_parties_decision', use_alter=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['case_parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_key', 'version', name='uq_case_parties_key_version')
    )
    op.create_index('ix_case_parties_case_layer', 'case_parties', ['case_id', 'layer'], unique=False)
    op.create_index('ix_case_parties_party_key', 'case_parties', ['party_key'], unique=False)
    op.create_index('uq_case_parties_current', 'case_parties', ['case_id', 'party_key'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('claim_directions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_direction_key', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('confirm_decision_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('CANDIDATE','CONFIRMED','SUPERSEDED','REJECTED')", name='ck_claim_directions_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['confirm_decision_id'], ['human_decisions.id'], name='fk_claim_directions_decision', use_alter=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['claim_directions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_direction_key', 'version', name='uq_claim_directions_key_version')
    )
    op.create_index('ix_claim_directions_case_current', 'claim_directions', ['case_id', 'is_current'], unique=False)
    op.create_index('uq_claim_directions_current', 'claim_directions', ['claim_direction_key'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('evidence_items',
    sa.Column('row_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('acceptance', sa.String(length=32), nullable=False),
    sa.Column('organizer_run_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("acceptance IN ('PENDING','ACCEPTED','EXCLUDED')", name='ck_evidence_acceptance'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('id', 'version', name='uq_evidence_items_id_version')
    )
    op.create_index('ix_evidence_items_case_current', 'evidence_items', ['case_id', 'is_current'], unique=False)
    op.create_index('uq_evidence_items_current', 'evidence_items', ['id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_key', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('confirm_decision_id', sa.UUID(), nullable=True),
    sa.Column('analyst_run_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("importance IN ('CORE','SUPPORTING','BACKGROUND')", name='ck_facts_importance'),
    sa.CheckConstraint("status IN ('CANDIDATE','CONFIRMED','REJECTED','SUPERSEDED')", name='ck_facts_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['confirm_decision_id'], ['human_decisions.id'], name='fk_facts_decision', use_alter=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['facts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_key', 'version', name='uq_facts_key_version')
    )
    op.create_index('ix_facts_case_status_current', 'facts', ['case_id', 'status', 'is_current'], unique=False)
    op.create_index('uq_facts_current', 'facts', ['fact_key'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('human_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IN ('CONFIRMED','REJECTED','SELECTED','AMENDED')", name='ck_human_decisions_result'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name='fk_human_decisions_instance', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_human_decisions_case', 'human_decisions', ['case_id', 'created_at'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('related_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyst_run_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("layer IN ('CANDIDATE','CONFIRMED','REJECTED','SUPERSEDED')", name='ck_issues_layer'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_case', 'issues', ['case_id'], unique=False)
    op.create_table('legal_theories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('theory_summary', sa.Text(), nullable=False),
    sa.Column('norms_suggested_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('analyst_run_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("layer IN ('CANDIDATE','CONFIRMED','REJECTED','SUPERSEDED')", name='ck_legal_theories_layer'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_theories_case', 'legal_theories', ['case_id'], unique=False)
    op.create_table('system_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('command_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACCEPTED','REJECTED','DONE')", name='ck_system_commands_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name='fk_system_commands_instance', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_commands_case', 'system_commands', ['case_id', 'created_at'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_precision', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('fact_key', sa.UUID(), nullable=True),
    sa.Column('evidence_item_id', sa.UUID(), nullable=True),
    sa.Column('related_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyst_run_id', sa.UUID(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("layer IN ('CANDIDATE','CONFIRMED','REJECTED','SUPERSEDED')", name='ck_timeline_layer'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_case', 'timeline_events', ['case_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('skill_code', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_human_gate', sa.Boolean(), nullable=False),
    sa.Column('gate_type', sa.String(length=64), nullable=True),
    sa.Column('on_failure_policy', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_workflow_nodes_template_code'),
    sa.UniqueConstraint('template_id', 'order_index', name='uq_workflow_nodes_template_order')
    )
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parsed_intent_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_decision_id', sa.UUID(), nullable=True),
    sa.Column('related_command_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER','AGENT','SYSTEM')", name='ck_agent_messages_role'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name='fk_agent_messages_instance', use_alter=True),
    sa.ForeignKeyConstraint(['related_command_id'], ['system_commands.id'], ),
    sa.ForeignKeyConstraint(['related_decision_id'], ['human_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_messages_case', 'agent_messages', ['case_id', 'created_at'], unique=False)
    op.create_table('extracted_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('extraction_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('full_text_ref', sa.String(length=1000), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED')", name='ck_extracted_contents_status'),
    sa.ForeignKeyConstraint(['material_id'], ['case_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'extraction_method', 'extraction_version', name='uq_extracted_contents_material_method_version')
    )
    op.create_index('ix_extracted_contents_material', 'extracted_contents', ['material_id', 'created_at'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('waiting_reason', sa.String(length=200), nullable=True),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','WAITING_USER','WAITING_RETRY','SUCCEEDED','FAILED','CANCELLED')", name='ck_workflow_instances_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['current_node_id'], ['workflow_nodes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_instances_case_status', 'workflow_instances', ['case_id', 'status'], unique=False)
    op.create_table('node_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot_ref', sa.String(length=1000), nullable=True),
    sa.Column('output_ref', sa.String(length=1000), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','WAITING_USER','FAILED','SUCCEEDED')", name='ck_node_runs_status'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'node_id', 'attempt', name='uq_node_runs_attempt')
    )
    op.create_table('source_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('extracted_content_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.Integer(), nullable=True),
    sa.Column('character_start', sa.Integer(), nullable=False),
    sa.Column('character_end', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_hash', sa.String(length=64), nullable=False),
    sa.Column('bbox_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('extraction_version', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('character_start >= 0 AND character_end > character_start', name='ck_source_spans_offsets'),
    sa.ForeignKeyConstraint(['extracted_content_id'], ['extracted_contents.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['case_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_spans_ec_start', 'source_spans', ['extracted_content_id', 'character_start'], unique=False)
    op.create_index('ix_source_spans_material_page', 'source_spans', ['material_id', 'page'], unique=False)
    op.create_table('document_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('body_structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('based_on_confirmation_set_hash', sa.String(length=128), nullable=False),
    sa.Column('writer_run_id', sa.UUID(), nullable=True),
    sa.Column('stale_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','IN_REVIEW','APPROVED_BY_LAWYER','STALE')", name='ck_document_drafts_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['writer_run_id'], ['node_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'doc_type', 'version', name='uq_document_drafts_version')
    )
    op.create_index('ix_document_drafts_case', 'document_drafts', ['case_id', 'doc_type'], unique=False)
    op.create_table('evidence_item_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_version', sa.Integer(), nullable=False),
    sa.Column('source_span_id', sa.UUID(), nullable=False),
    sa.Column('role_in_item', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role_in_item IN ('PRIMARY','ATTACHMENT','SIGNATURE_PAGE')", name='ck_evidence_item_span_role'),
    sa.ForeignKeyConstraint(['evidence_item_id', 'evidence_item_version'], ['evidence_items.id', 'evidence_items.version'], name='fk_evidence_item_spans_item'),
    sa.ForeignKeyConstraint(['source_span_id'], ['source_spans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_item_id', 'evidence_item_version', 'source_span_id', name='uq_evidence_item_spans')
    )
    op.create_table('fact_evidence_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_version', sa.Integer(), nullable=False),
    sa.Column('source_span_id', sa.UUID(), nullable=True),
    sa.Column('link_role', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("link_role IN ('PROVES','CORROBORATES','CONTEXT')", name='ck_fact_link_role'),
    sa.CheckConstraint("status IN ('ACTIVE','STALE','VOID')", name='ck_fact_link_status'),
    sa.ForeignKeyConstraint(['evidence_item_id', 'evidence_item_version'], ['evidence_items.id', 'evidence_items.version'], name='fk_fact_links_evidence'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['source_span_id'], ['source_spans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_links_evidence', 'fact_evidence_links', ['evidence_item_id'], unique=False)
    op.create_index('ix_fact_links_fact', 'fact_evidence_links', ['fact_id'], unique=False)
    op.create_table('skill_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('skill_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED')", name='ck_skill_executions_status'),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_run_id')
    )
    op.create_table('draft_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.String(length=100), nullable=False),
    sa.Column('citation_kind', sa.String(length=32), nullable=False),
    sa.Column('fact_key', sa.UUID(), nullable=True),
    sa.Column('fact_version', sa.Integer(), nullable=True),
    sa.Column('evidence_item_id', sa.UUID(), nullable=True),
    sa.Column('evidence_item_version', sa.Integer(), nullable=True),
    sa.Column('requires_lawyer_confirm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(fact_key IS NOT NULL) OR (evidence_item_id IS NOT NULL) OR (citation_kind = 'ANNOTATION')", name='ck_draft_citations_target'),
    sa.ForeignKeyConstraint(['draft_id'], ['document_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_draft_citations_draft', 'draft_citations', ['draft_id'], unique=False)
    op.create_index('ix_draft_citations_evidence', 'draft_citations', ['evidence_item_id', 'evidence_item_version'], unique=False)
    op.create_index('ix_draft_citations_fact', 'draft_citations', ['fact_key', 'fact_version'], unique=False)
    # ### end Alembic commands ###

    # Seed PLEADING_PREP workflow template (data only; no Runtime).
    import uuid

    template_id = uuid.UUID("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
    op.execute(
        sa.text(
            "INSERT INTO workflow_templates (id, code, name, version) "
            "VALUES (:id, 'PLEADING_PREP', '起诉准备', 1)"
        ).bindparams(id=template_id)
    )
    nodes = [
        ("N0_CREATE", "创建案件", None, 0, False, None),
        ("N1_PARSE", "材料解析", None, 1, False, None),
        ("N2_ORGANIZE", "证据整理", "EvidenceOrganizer", 2, False, None),
        ("N3_CONFIRM_EVIDENCE", "确认证据", None, 3, True, "EVIDENCE"),
        ("N4_ANALYZE", "案件分析", "CaseAnalyst", 4, False, None),
        ("N5_CONFIRM_PARTIES", "确认当事人", None, 5, True, "PARTY"),
        ("N6_CONFIRM_FACTS", "确认核心事实", None, 6, True, "FACT"),
        ("N7_CONFIRM_CLAIMS", "确认诉讼请求方向", None, 7, True, "CLAIM"),
        ("N8_WRITE", "起草起诉状", "PleadingWriter", 8, False, None),
        ("N9_REVIEW", "律师审核草稿", None, 9, True, "DRAFT_REVIEW"),
    ]
    for code, name, skill, order_index, is_gate, gate_type in nodes:
        op.execute(
            sa.text(
                "INSERT INTO workflow_nodes "
                "(id, template_id, code, name, skill_code, order_index, is_human_gate, gate_type, on_failure_policy) "
                "VALUES (:id, :tid, :code, :name, :skill, :ord, :gate, :gate_type, 'RETRY')"
            ).bindparams(
                id=uuid.uuid4(),
                tid=template_id,
                code=code,
                name=name,
                skill=skill,
                ord=order_index,
                gate=is_gate,
                gate_type=gate_type,
            )
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_draft_citations_fact', table_name='draft_citations')
    op.drop_index('ix_draft_citations_evidence', table_name='draft_citations')
    op.drop_index('ix_draft_citations_draft', table_name='draft_citations')
    op.drop_table('draft_citations')
    op.drop_table('skill_executions')
    op.drop_index('ix_fact_links_fact', table_name='fact_evidence_links')
    op.drop_index('ix_fact_links_evidence', table_name='fact_evidence_links')
    op.drop_table('fact_evidence_links')
    op.drop_table('evidence_item_spans')
    op.drop_index('ix_document_drafts_case', table_name='document_drafts')
    op.drop_table('document_drafts')
    op.drop_index('ix_source_spans_material_page', table_name='source_spans')
    op.drop_index('ix_source_spans_ec_start', table_name='source_spans')
    op.drop_table('source_spans')
    op.drop_table('node_runs')
    op.drop_index('ix_workflow_instances_case_status', table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index('ix_extracted_contents_material', table_name='extracted_contents')
    op.drop_table('extracted_contents')
    op.drop_index('ix_agent_messages_case', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_table('workflow_nodes')
    op.drop_index('ix_timeline_case', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_system_commands_case', table_name='system_commands')
    op.drop_table('system_commands')
    op.drop_index('ix_legal_theories_case', table_name='legal_theories')
    op.drop_table('legal_theories')
    op.drop_index('ix_issues_case', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_human_decisions_case', table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index('uq_facts_current', table_name='facts', postgresql_where=sa.text('is_current = true'))
    op.drop_index('ix_facts_case_status_current', table_name='facts')
    op.drop_table('facts')
    op.drop_index('uq_evidence_items_current', table_name='evidence_items', postgresql_where=sa.text('is_current = true'))
    op.drop_index('ix_evidence_items_case_current', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('uq_claim_directions_current', table_name='claim_directions', postgresql_where=sa.text('is_current = true'))
    op.drop_index('ix_claim_directions_case_current', table_name='claim_directions')
    op.drop_table('claim_directions')
    op.drop_index('uq_case_parties_current', table_name='case_parties', postgresql_where=sa.text('is_current = true'))
    op.drop_index('ix_case_parties_party_key', table_name='case_parties')
    op.drop_index('ix_case_parties_case_layer', table_name='case_parties')
    op.drop_table('case_parties')
    op.drop_index('ix_materials_case_created', table_name='case_materials')
    op.drop_table('case_materials')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_case_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('workflow_templates')
    op.drop_index('ix_cases_owner_updated', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
